Use json_extract_path_text() to get renewal count from circulation_loans
folio-org/folio-analytics pull request #349
Opened 2021-02-10 17:45 UTC by wafschneider

Fixes an issue with derived table `loans_items` when a system has no renewals. Based on `stable` branch (`0.9-release` does not have a `renewal_count` column in the `loans_items` table).

2021-02-10 21:14 UTC, nassibnassar commented
In the future we should probably make PRs on main or release branches rather than stable.  The documentation about this in CONTRIBUTING.md is wrong; I will fix it.

In this case it does not matter because stable and main are being synchronized during the feature freeze.

2021-02-10 21:19 UTC, nassibnassar commented
Also we try not to make PRs from this repository but from forks.

2021-02-10 21:27 UTC, nassibnassar requested changes

2021-02-10 21:27 UTC, nassibnassar commented on sql/derived_tables/loans_items.sql
> +    json_extract_path_text(cl.data, 'renewalCount')::int8 AS renewal_count
We are using `bigint` for `renewalCount`.  I can make this change if needed.

2021-02-12 14:54 UTC, wafschneider commented
Sorry for failing to follow the contributor guidelines! Closing this PR and opening a new one against `main` (with the request datatype change).

2021-02-12 14:54 UTC, closed without merging