Instance Contributors Metadb derived table
folio-org/folio-analytics pull request #543
Opened 2022-02-04 18:19 UTC by jenmawe

Porting over instance contributors derived table from LDP to Metadb. No issue associated with pull request

2022-02-08 13:07 UTC, jenmawe commented
I just updated this file with the changes requested from other submissions. No "" around jsonb, added ordinality and made that lowercase.

2022-02-10 05:17 UTC, adoerrer requested changes
I appologize I thought I've finished my review already...
The query works great, I've found only some smaller issues and it is missing in  the runlist, thank you.

2022-02-10 05:17 UTC, adoerrer commented on sql_metadb/derived_tables/instance_contributors.sql
> +	cntt."name" AS contributor_name_type_name,
I assume Dbeaver had sneaked in the quotes on name as well.

2022-02-10 15:09 UTC, adoerrer approved these changes
Look and works great, thanks!

2022-02-23 14:45 UTC, amzoss approved these changes
Looks great!

2022-02-23 14:55 UTC, amzoss commented
- [x] Query runs
- [x] Data output makes sense
- [x] Data types look correct
- [x] Query logic seems correct
- [x] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)
- For derived tables:
    - [x] query has indexes on columns
    - [x] vacuum analyze has been added to the bottom
    - [x] table appears in runlist.txt at an appropriate point

2022-02-24 23:02 UTC, nassibnassar commented on sql_metadb/derived_tables/instance_contributors.sql
> +		folio_inventory.instance i
We are using `AS` here even though Postgres does not require it.  I will add this.

2022-02-24 23:23 UTC, merged