new metadb derived table Holdings statements
folio-org/folio-analytics pull request #568
Opened 2022-02-22 18:28 UTC by natalyapik

add new metadb derived table for holdings also added to runlist

2022-02-24 16:13 UTC, jenmawe requested changes
The only thing I saw was that in the Create Index at the bottom you have note instead of public_note. Once I changed that, the query ran.
- [] Query runs
- [x] Data output makes sense
- [x] Data types look correct
- [x] Query logic seems correct
- [] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [x] query has indexes on columns
- [x] vacuum analyze has been added to the bottom
- [x] table appears in runlist.txt at an appropriate point

2022-03-01 15:59 UTC, adoerrer approved these changes
After the update query looks good, thank you! 

- [x] Query runs
- [x] Data output makes sense
- [x] Data types look correct
- [x] Query logic seems correct
- [x] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [x] query has indexes on columns
- [x] vacuum analyze has been added to the bottom
- [x] table appears in runlist.txt at an appropriate point

2022-03-04 15:11 UTC, jenmawe requested changes
On line 42, just a change from note to public_note

2022-03-07 15:23 UTC, jenmawe approved these changes

2022-03-07 23:14 UTC, nassibnassar commented on sql_metadb/derived_tables/holdings_statements.sql
> +    FROM folio_inventory.holdings_record h
We are tending to use `FROM <table> AS <alias>`.  I will make this change.

2022-03-07 23:15 UTC, nassibnassar commented on sql_metadb/derived_tables/holdings_statements.sql
> +    LEFT JOIN folio_inventory.instance i ON hs.instance_id = i.id
And again here.  I will make the change.

2022-03-07 23:21 UTC, merged