RM - port derived table invoice_lines_fund_distributions for metadb
folio-org/folio-analytics pull request #588
Opened 2022-03-07 22:08 UTC by sbeltaine

2022-03-08 14:12 UTC, jenmawe requested changes
- [x] Query runs
- [x] Data output makes sense
- [x] Data types look correct
- [x] Query logic seems correct
- [x] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [x] query has indexes on columns
- [x] vacuum analyze has been added to the bottom
- [] table appears in runlist.txt at an appropriate point

2022-03-08 17:09 UTC, lib-eric approved these changes
@sbeltaine No change since I last approved.

Did you mean to re-request review from @jenmawe ?

I'm guessing just need to double check the other PR for the runlist update. Little confusing since two different requests.

2022-03-09 23:58 UTC, nassibnassar commented on sql_metadb/derived_tables/invoice_lines_fund_distributions.sql
> +--invoice_lines_fund_distributions
Missing description: https://github.com/folio-org/folio-analytics/issues/596

2022-03-10 00:10 UTC, nassibnassar commented on sql_metadb/derived_tables/invoice_lines_fund_distributions.sql
> +        jsonb_extract_path_text(lines.jsonb, 'total')::numeric(12,2) AS invoice_line_total
Please note that monetary values for derived tables in Metadb should be `numeric(19,4)`.  I will make the change here.

2022-03-10 00:10 UTC, nassibnassar commented on sql_metadb/derived_tables/invoice_lines_fund_distributions.sql
> +        jsonb_extract_path_text(dist.data, 'value')::numeric AS fund_distribution_value,
Please note that monetary values for derived tables in Metadb should be `numeric(19,4)`.  I will make the change here.

2022-03-10 00:24 UTC, nassibnassar commented on sql_metadb/derived_tables/invoice_lines_fund_distributions.sql
> +        CROSS JOIN jsonb_array_elements(jsonb_extract_path(lines.jsonb, 'fundDistributions')) AS dist(data)
I'm not sure this is correct.  I will try to fix it.

2022-03-10 00:35 UTC, nassibnassar commented on sql_metadb/derived_tables/invoice_lines_fund_distributions.sql
> +    invoice_line_total
It is probably a good idea to qualify column names with the table name or alias when multiple tables are involved.

Also I wonder about the order of these columns.  For clarity we usually place non-array columns from the base tables before array columns, followed by ordinality, though these are not requirements.

2022-03-10 00:36 UTC, nassibnassar commented
I think it might be a good idea to spend some more time with this query before merging.

2022-04-06 21:55 UTC, nassibnassar commented on sql_metadb/derived_tables/invoice_lines_fund_distributions.sql
> +        CROSS JOIN jsonb_array_elements(jsonb_extract_path(lines.jsonb, 'fundDistributions')) AS dist(data)
Correction, this may be OK.

2022-04-06 21:57 UTC, nassibnassar commented
@sbeltaine This PR may need more work.

2022-04-28 23:08 UTC, nassibnassar requested changes
At least one change is requested in comments

2022-07-07 22:38 UTC, merged