MM, Metadb derived table Instance_ext changed Date to timestamptz
folio-org/folio-analytics pull request #595
Opened 2022-03-09 20:17 UTC by jenmawe

For system created FOLIO fields of cataloged and updated date change casting to timestamptz.

2022-03-11 15:39 UTC, lib-eric approved these changes
Small change -- thanks!

2022-03-21 08:14 UTC, adoerrer requested changes
Thanks you for changing the date type to the more accurate timestampz. The query runs and looks goods, but I'd suggest to create indexes for `title` and `index_title` as well.

- [x] Query runs
- [x] Data output makes sense
- [x] Data types look correct
- [x] Query logic seems correct
- [x] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [] query has indexes on columns
- [x] vacuum analyze has been added to the bottom
- [x] table appears in runlist.txt at an appropriate point

2022-03-21 12:40 UTC, nassibnassar commented
@adoerrer @jenmawe I think `title` and `index_title` may tend to be large varchars and unsuitable for the default index type.  They should probably be left without an index for now.

2022-03-21 12:53 UTC, jenmawe commented
> @adoerrer @jenmawe I think `title` and `index_title` may tend to be large varchars and unsuitable for the default index type. They should probably be left without an index for now.

Both can get really long. Let me remove these from the index.

2022-03-21 14:39 UTC, adoerrer approved these changes
Oh, I didn't know  `title` and `index_title` can get that big. Since they are not created atm @jenmawe you don't have to do anything. 
Thanks, for this work!

2022-04-06 23:50 UTC, nassibnassar requested changes

2022-04-06 23:50 UTC, nassibnassar commented on sql_metadb/derived_tables/instance_ext.sql
> +    jsonb_extract_path_text(i.jsonb, 'metadata', 'createdDate')::timestamptz AS created_date,
The `createdDate` data do not appear to have a timezone.  It should probably have the `timestamp` data type.

2022-04-28 23:23 UTC, nassibnassar commented
It looks like you changed `updatedDate` instead of `createdDate`.

2022-04-29 12:55 UTC, jenmawe commented
> It looks like you changed `updatedDate` instead of `createdDate`.

Sorry about that. I just updated the createdDate. This should be good to go.

2022-05-06 20:39 UTC, nassibnassar commented
Almost!  The `updatedDate` field should be changed back to `timestamptz`.

2022-05-09 13:55 UTC, jenmawe commented
> Almost! The `updatedDate` field should be changed back to `timestamptz`.

Changed it back.

2022-05-14 22:23 UTC, merged