po_lines_location.sql
folio-org/folio-analytics pull request #599
Opened 2022-03-22 14:33 UTC by arthur-aguilera

Port po_lines_location to metadb.

2022-03-22 14:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/folio-analytics?pullRequest=599) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/folio-analytics?pullRequest=599) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/folio-analytics?pullRequest=599) it.</sub>

2022-03-24 08:25 UTC, adoerrer requested changes
Thank you, Arthur! The query looks and works great overall, but I've some minor suggestions on the data type casts and a formal naming consistency.

Beside that you need to add the derived table query to the [runlist.txt](https://github.com/arthur-aguilera/folio-analytics/blob/main/sql_metadb/derived_tables/runlist.txt)  So it can  be run automatically.


- [x] Query runs
- [x] Data output makes sense
- [x] Data types look correct
- [x] Query logic seems correct
- [x] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)
For derived tables:
- [x] query has indexes on columns
- [x] vacuum analyze has been added to the bottom
- [x] table appears in runlist.txt at an appropriate point and with correct file name

2022-03-24 08:25 UTC, adoerrer commented on po_lines_location
> +    pol_location.pol_loc_id,
You might want to cast pol_loc_id as well to uuid data type.

2022-03-24 08:25 UTC, adoerrer commented on po_lines_location
> +    pol_location.pol_loc_quant_phys,
I think all of them could be casted  to `int`.

2022-03-24 08:25 UTC, adoerrer commented on po_lines_location
> +        jsonb_extract_path_text(locations.data, 'quantityPhysical') AS pol_loc_quant_phys
Perhaps `pol_loc_quant_phys` could named as `pol_loc_qty_phys` just for naming consistency.

2022-05-03 15:15 UTC, adoerrer approved these changes
Now that looks and works great. Thank you, Arthur!

2022-06-08 23:46 UTC, nassibnassar commented
Could we have a complete description for the pull request:  https://github.com/folio-org/folio-analytics/blob/main/CONTRIBUTING.md#2-commits-and-pull-requests

2022-06-09 06:48 UTC, adoerrer commented
> Could we have a complete description for the pull request: https://github.com/folio-org/folio-analytics/blob/main/CONTRIBUTING.md#2-commits-and-pull-requests

I think this is my bad. I just advised arthur to enter the related issue. 
@arthur-aguilera 
Please, add something like: This ports the derived table po_lines_locations to Metadb
Thanks!

2022-07-07 23:42 UTC, merged