Create MetaDB derived item_statistical_codes
folio-org/folio-analytics pull request #602
Opened 2022-03-25 20:55 UTC by lib-eric

Pulling from some unpacked tables - requiring casting of IDs on the `LEFT JOIN`s

2022-04-04 15:48 UTC, eliana-flo commented
Looking good! All tests passed for me. 

Query runs
- [X] Data output makes sense
- [X] Data types look correct
- [X] Query logic seems correct
- [X] Column names make sense and are spelled correctly
- [X] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [X] query has indexes on columns
- [X] vacuum analyze has been added to the bottom
- [X] table appears in runlist.txt at an appropriate point and with correct file name

2022-04-04 15:50 UTC, eliana-flo approved these changes
Looks like I did things a little out of order. :)

2022-04-07 10:48 UTC, stdombek requested changes
- [X] Query runs
- [X] Data output makes sense
- [ ] Data types look correct
- [X] Query logic seems correct
- [X] Column names make sense and are spelled correctly
- [X] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [X] query has indexes on columns
- [X] vacuum analyze has been added to the bottom
- [X] table appears in runlist.txt at an appropriate point

2022-04-07 10:48 UTC, stdombek commented on sql_metadb/derived_tables/item_statistical_codes.sql
> +    items_statistical_codes.statistical_code_id,
Should be of type uuid.

2022-04-07 10:48 UTC, stdombek commented on sql_metadb/derived_tables/item_statistical_codes.sql
> +    sc__t.statistical_code_type_id,
Should be of type uuid.

2022-04-12 13:59 UTC, lib-eric commented on sql_metadb/derived_tables/item_statistical_codes.sql
> +    items_statistical_codes.statistical_code_id,
Cast `statistical_code_id` to `uuid`

2022-04-29 01:09 UTC, nassibnassar requested changes
Could we get a clearer summary in the PR description?

2022-05-24 14:42 UTC, adoerrer commented
> Could we get a clearer summary in the PR description?

I'm not sure if this has happened already. @lib-eric could you please take a look on that? Thanks!

2022-06-09 00:28 UTC, merged