Instance_identifiers
folio-org/folio-analytics pull request #607
Opened 2022-04-05 17:04 UTC by natalyapik

create new derived metadb table instance_identifiers

2022-04-22 15:56 UTC, stdombek commented on sql_metadb/derived_tables/instance_identifiers.sql
> +    jsonb_extract_path_text(idents.jsonb, 'identifierTypeId') AS identifier_type_id,
"identifier_type_id" should be of data type uuid.

2022-04-22 15:56 UTC, stdombek requested changes
- [X] Query runs
- [X] Data output makes sense
- [ ] Data types look correct
- [X] Query logic seems correct
- [X] Column names make sense and are spelled correctly
- [X] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [X] query has indexes on columns
- [X] vacuum analyze has been added to the bottom
- [X] table appears in runlist.txt at an appropriate point

2022-04-27 17:38 UTC, adoerrer requested changes
Thanks! Looks good but there're two minor changes to  do.
- [x] Query runs
- [x] Data output makes sense
- [] Data types look correct
- [x] Query logic seems correct
- [x] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)
For derived tables:
- [x] query has indexes on columns
- [x] vacuum analyze has been added to the bottom
- [x] table appears in runlist.txt at an appropriate point and with correct file name

2022-04-27 17:38 UTC, adoerrer commented on sql_metadb/derived_tables/instance_identifiers.sql
> +CREATE INDEX ON instance_identifiers (identifier_ordinaliry);
There's a little type in the column name. It should be: `identifier_ordinality`

2022-06-10 07:42 UTC, stdombek approved these changes
All queries:
- [X] Pull request has a complete description
- [X] Query runs without errors
- [X] Query output is correct
- [X] Query logic is clear and well documented
- [X] Query is readable and properly indented
- [X] Table and column names are in all-lowercase
- [X] Quotation marks are used only where necessary

Derived tables:
- [X] Query begins with user documentation in comment lines
- [X] File name is listed in `runlist.txt` after dependencies
- [X] All columns have indexes
- [X] Table is vacuumed and analyzed

PR has a very minimal description, but possible.

2022-06-29 07:54 UTC, adoerrer approved these changes
Thank you, Natalya. Looks and runs great.

2022-07-07 23:58 UTC, merged