MM MetaDB Derived Table Instance notes
folio-org/folio-analytics pull request #614
Opened 2022-05-03 16:54 UTC by jenmawe

New ported derived table for metaDB for instance_notes

2022-05-18 20:46 UTC, natalyapik commented
Axel, could you please ran this sql again? Mine is saying table folio_inventory.instance__t does not exists. I can see it in the directory. Not sure if I m doing something incorrectly.Thank you.

2022-05-19 14:50 UTC, natalyapik commented
all looks good, may be just change INSTANCE to lower case as in other queries: LEFT JOIN folio_inventory.**INSTANCE** as in other queries?

2022-05-19 15:03 UTC, natalyapik requested changes

2022-05-19 15:03 UTC, natalyapik commented on sql_metadb/derived_tables/instance_notes.sql
> +	LEFT JOIN folio_inventory.INSTANCE AS inst ON inst.id::uuid = it.id::uuid
lower case instance in folio_inventory.INSTANCE

2022-05-24 14:03 UTC, adoerrer approved these changes
Runs great, sql and results looks good, thanks!

All queries:
- [x] Pull request has a complete description
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-05-24 14:17 UTC, natalyapik approved these changes
yep, looks great

2022-06-09 02:18 UTC, merged