Holdings administrative notes
folio-org/folio-analytics pull request #641
Opened 2022-05-31 17:05 UTC by natalyapik

new metadb derived table for holdings_administrative_notes

2022-06-01 15:22 UTC, jenmawe requested changes
All queries:
- [x] Pull request has a complete description
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
**- [] File name is listed in `runlist.txt` after dependencies**
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-06-09 00:41 UTC, nassibnassar commented
- [ ] Pull request has a complete description
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed

2022-06-15 21:03 UTC, lib-eric requested changes
Changes for singular column names

All queries:
- [x] Pull request has a complete description
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [ ] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-06-15 21:03 UTC, lib-eric commented on sql_metadb/derived_tables/holdings_administrative_notes.sql
> +    adminNotes.jsonb #>> '{}' AS administrative_notes,
Advised to use singular column name and all-lowercase table names
```suggestion
    admin_notes.jsonb #>> '{}' AS administrative_note,
```

2022-06-15 21:03 UTC, lib-eric commented on sql_metadb/derived_tables/holdings_administrative_notes.sql
> +    adminNotes.ordinality AS administrative_notes_ordinality
Advised to use singular column name and all-lowercase table names
```suggestion
    admin_notes.ordinality AS administrative_note_ordinality
```

2022-06-15 21:03 UTC, lib-eric commented on sql_metadb/derived_tables/holdings_administrative_notes.sql
> +    CROSS JOIN LATERAL jsonb_array_elements(jsonb_extract_path(hld.jsonb, 'administrativeNotes')) WITH ORDINALITY AS adminNotes (jsonb);
All-lowercase table names
```suggestion
    CROSS JOIN LATERAL jsonb_array_elements(jsonb_extract_path(hld.jsonb, 'administrativeNotes')) WITH ORDINALITY AS admin_notes (jsonb);
```

2022-06-15 21:03 UTC, lib-eric commented on sql_metadb/derived_tables/holdings_administrative_notes.sql
> +CREATE INDEX ON holdings_administrative_notes (administrative_notes);
Advised to use singular column name
```suggestion
CREATE INDEX ON holdings_administrative_notes (administrative_note);
```

2022-06-15 21:03 UTC, lib-eric commented on sql_metadb/derived_tables/holdings_administrative_notes.sql
> +CREATE INDEX ON holdings_administrative_notes (administrative_notes_ordinality);
Advised to use singular column name
```suggestion
CREATE INDEX ON holdings_administrative_notes (administrative_note_ordinality);
```

2022-06-28 13:01 UTC, lib-eric approved these changes
Looks good - thank you!

2022-07-01 14:39 UTC, jenmawe requested changes
We use holdings as in a holdings record. Could you update holding_id to holdings_id and the others like this?

2022-07-08 01:18 UTC, nassibnassar commented on sql_metadb/derived_tables/holdings_administrative_notes.sql
> +CREATE INDEX ON holdings_administrative_notes (holdinsg_hrid);
Typo

2022-07-15 19:42 UTC, jenmawe approved these changes

2022-07-15 22:53 UTC, merged