MM New derived table Holdings tags
folio-org/folio-analytics pull request #642
Opened 2022-05-31 17:27 UTC by natalyapik

create new metadb derived table holdings_tags

2022-06-09 00:41 UTC, nassibnassar commented
- [ ] Pull request has a complete description
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed

2022-06-16 14:47 UTC, jenmawe requested changes

2022-06-16 14:47 UTC, jenmawe commented on sql_metadb/derived_tables/holdings_tags
> +    hldtags.jsonb #>> '{}' AS holdings_tags,
This column name should probably be holdings_tags. I changed it for the instance tag column name to be singular. This is just to follow that all column names be singular.

2022-06-16 14:47 UTC, jenmawe commented on sql_metadb/derived_tables/holdings_tags
> +    hldtags.ordinality AS holdings_tags_ordinality
To follow the comment above, change tags to tag here

2022-06-29 08:48 UTC, adoerrer requested changes
* [ x]  Pull request has a complete description
     * [x]  Query runs without errors
     * [x]  Query output is correct
     * [x ]  Query logic is clear and well documented
     * [x]  Query is readable and properly indented
     * [x]  Table and column names are in all-lowercase 
     * [x]  Quotation marks are used only where necessary 
     * [x]  Query begins with user documentation in comment lines 
     * [x]  File name is listed in `runlist.txt` after dependencies 
     * [x]  All columns have indexes
     * [x]  Table is vacuumed and analyzed

Thank you, Natalya! Although the query runs great and checklist is all checked there are some minor change requests.

As Jennifer already mentioned please change the column name regarding tags to singular. And the query file is missing the `.sql ` suffix.

2022-06-30 11:08 UTC, adoerrer approved these changes
Perfect, columnnames look good now. Thank you, Natalya!

2022-07-01 14:36 UTC, jenmawe requested changes
Hi @natalyapik ,

We did decide to use holdings rather than holding in MM as we refer to a holdings record. Anyway, this one still uses the plural but the term that follows won't like holdings_tag or holdings_note. Sorry for the confusion.

2022-07-01 14:36 UTC, jenmawe commented on sql_metadb/derived_tables/holdings_tags.sql
> +    hd.id AS holding_id,
For MM, we still want to use holdings. This is how we use it in our other queries.

2022-07-01 14:36 UTC, jenmawe commented on sql_metadb/derived_tables/holdings_tags.sql
> +    hd.hrid AS holding_hrid,
holdings_hrid

2022-07-01 14:36 UTC, jenmawe commented on sql_metadb/derived_tables/holdings_tags.sql
> +    hldtags.jsonb #>> '{}' AS holding_tag,
holdings_tag

2022-07-01 14:36 UTC, jenmawe commented on sql_metadb/derived_tables/holdings_tags.sql
> +    hldtags.ordinality AS holding_tag_ordinality
holdings_tag_ordinality

2022-07-01 14:36 UTC, jenmawe commented on sql_metadb/derived_tables/holdings_tags.sql
> +CREATE INDEX ON holdings_tags (holdins_id);
missing the g for holdings_id

2022-07-01 14:36 UTC, jenmawe commented on sql_metadb/derived_tables/holdings_tags.sql
> +CREATE INDEX ON holdings_tags (holding_hrid);
holdings_hrid and the same for those below

2022-07-14 12:16 UTC, adoerrer approved these changes
Thanks @jenmawe  for catching the spelling issues. I think this is now ready to go.

@jenmawe Do you want to re-review the changes as well?  Thanks!

2022-07-15 19:43 UTC, jenmawe approved these changes

2022-07-15 23:04 UTC, merged