RM New metadb derived table po_acq_unit_ids
folio-org/folio-analytics pull request #643
Opened 2022-05-31 18:03 UTC by natalyapik

2022-06-01 15:36 UTC, jenmawe requested changes
All queries:
**- [] Pull request has a complete description**, add description to PR
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
**- [] Quotation marks are used only where necessary** au."name" -> au.name 

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-06-09 00:41 UTC, nassibnassar commented
- [ ] Pull request has a complete description
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed

2022-06-24 14:56 UTC, stdombek requested changes
- [ ] Pull request has a complete description
- [X] Query runs without errors
- [ ] Query output is correct
- [X] Query logic is clear and well documented
- [ ] Query is readable and properly indented
- [X] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary
- [X] Query begins with user documentation in comment lines
- [X] File name is listed in runlist.txt after dependencies
- [X] All columns have indexes
- [X] Table is vacuumed and analyzed

Very good. Please check the data type in line 8 and add a description to the PR. 

Query is not properly indented from line 5. The query should be one level to the left. But it's more because it's like that in other derived tables.

2022-06-24 14:56 UTC, stdombek commented on sql_metadb/derived_tables/po_acq_unit_ids
> +        acq_unit_ids.jsonb #>> '{}' AS po_acquisition_unit_id,
Please change to data type UUID.

2022-06-24 14:56 UTC, stdombek commented on sql_metadb/derived_tables/po_acq_unit_ids
> +        au."name" AS po_acquisition_unit_name
Please remove quotation marks.

2022-06-24 15:01 UTC, stdombek commented on sql_metadb/derived_tables/po_acq_unit_ids
> +        acq_unit_ids.jsonb #>> '{}' AS po_acquisition_unit_id,
from 
`acq_unit_ids.jsonb #>> '{}' AS po_acquisition_unit_id`
to
`CAST(acq_unit_ids.jsonb #>> '{}' AS uuid) AS po_acquisition_unit_id`

2022-06-29 09:59 UTC, adoerrer requested changes
> * [ ]  Pull request has a complete description
> 
>     * [x]  Query runs without errors
> 
>     * [x]  Query output is correct
> 
>     * [x]  Query logic is clear and well documented
> 
>     * [x]  Query is readable and properly indented
> 
>     * [x]  Table and column names are in all-lowercase
> 
>     * [x]  Quotation marks are used only where necessary
> 
>     * [x]  Query begins with user documentation in comment lines
> 
>     * [x]  File name is listed in `runlist.txt` after dependencies
> 
>     * [x]  All columns have indexes
> 
>     * [x]  Table is vacuumed and analyzed


Query is good overall but the suffix `.sql` for the query is missing and a PR description is missing- You can just add it to the first box in the conversation.

2022-06-30 06:59 UTC, stdombek approved these changes
- [ ] Pull request has a complete description
- [X] Query runs without errors
- [X] Query output is correct
- [X] Query logic is clear and well documented
- [X] Query is readable and properly indented
- [X] Table and column names are in all-lowercase
- [X] Quotation marks are used only where necessary
- [X] Query begins with user documentation in comment lines
- [X] File name is listed in `runlist.txt` after dependencies
- [X] All columns have indexes
- [X] Table is vacuumed and analyzed

PR has no description. I think it can be ignored here.

2022-07-01 10:48 UTC, adoerrer approved these changes
I'd agree @stdombek since it might only an echo of PR title

2022-07-06 06:41 UTC, stdombek reviewed
In metadb, the IDs are changed to uuid unless it is specifically intended to do so within the app and would cause a chain reaction with the other reports using that ID.

2022-07-06 13:22 UTC, stdombek approved these changes
- [ ] Pull request has a complete description
- [X] Query runs without errors
- [X] Query output is correct
- [X] Query logic is clear and well documented
- [X] Query is readable and properly indented
- [X] Table and column names are in all-lowercase
- [X] Quotation marks are used only where necessary
- [X] Query begins with user documentation in comment lines
- [X] File name is listed in `runlist.txt` after dependencies
- [X] All columns have indexes
- [X] Table is vacuumed and analyzed

PR has no description. It can be ignored here.

2022-07-08 01:24 UTC, merged