new po_instance.sql
folio-org/folio-analytics pull request #665
Opened 2022-08-19 16:50 UTC by natalyapik

2022-08-19 17:04 UTC, amzoss requested changes
Only one small change - the column named `location_name` should be named `pol_location_name`.

All queries:
- [x] Pull request has a complete description
- [ ] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-08-25 20:40 UTC, amzoss approved these changes
Thanks, looks good now!

- [x] Pull request has a complete description
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-08-25 20:59 UTC, eliana-flo approved these changes
Other than my small nitpick (see previous comment) this looks good and runs well.

All queries:
- [x] Pull request has a complete description
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

2022-08-25 20:59 UTC, eliana-flo commented on sql/derived_tables/po_instance.sql
>      po_purchase_orders.workflow_status AS po_wf_status,
I'm not sure if the abbreviation "wf" is clear enough. Maybe change to "po_workflow_status" or just "po_status"?

2022-09-07 13:37 UTC, amzoss approved these changes
Approving again, since there was a change in a variable name

2022-09-22 00:30 UTC, merged