new metadb derived table po_line_vendor_reference_number
folio-org/folio-analytics pull request #668
Opened 2022-08-25 19:20 UTC by natalyapik

2022-09-07 07:27 UTC, stdombek requested changes
- [ ] Pull request has a complete description
- [X] Query runs without errors
- [X] Query output is correct
- [X] Query logic is clear and well documented
- [X] Query is readable and properly indented with spaces (not tabs)
- [X] Table and column names are in all-lowercase
- [X] Quotation marks are used only where necessary
- [X] Query begins with user documentation in comment lines
- [X] File name is listed in `runlist.txt` after dependencies
- [X] All columns have indexes
- [X] Table is vacuumed and analyzed

Very good! 

- Please make the correction in the description. (line 1) 
- The indentation in the From Clause could be done at the same time. I don't see them that strictly now.
- Unfortunately, a description of the PR is missing.

2022-09-07 07:27 UTC, stdombek commented on sql_metadb/po_line_vendor_reference_number.sql
> +-- This derived table extracts refeence numbers from po_lines vendor details.
Please correct to 'reference'

2022-09-08 08:48 UTC, stdombek approved these changes
PR description is missing, but can now be included in the CHANGES.md. Therefore, the PR can be approved.

2022-10-26 18:51 UTC, scotttperry approved these changes
Pull request has a complete description
 Query runs without errors
 Query output is correct
 Query logic is clear and well documented
 Query is readable and properly indented with spaces (not tabs)
 Table and column names are in all-lowercase
 Quotation marks are used only where necessary
 Query begins with user documentation in comment lines
 File name is listed in runlist.txt after dependencies
 All columns have indexes
 Table is vacuumed and analyzed

2022-10-28 00:50 UTC, nassibnassar commented
The SQL file is in the wrong directory.  I will fix it before merging.

2022-10-28 00:52 UTC, merged