Update licenses_license_ext.sql
folio-org/folio-analytics pull request #679
Opened 2022-10-17 16:31 UTC by AlaoSUL

Comment on Columns to provide API Documentation Descriptions

Closes #636 

```
All queries:
- [ ] Release notes added or updated in CHANGES.md
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented with spaces (not tabs)
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed
```

2022-10-17 16:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/folio-analytics?pullRequest=679) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/folio-analytics?pullRequest=679) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/folio-analytics?pullRequest=679) it.</sub>

2022-10-20 10:28 UTC, stdombek requested changes
All queries:
- [ ] Release notes added or updated in CHANGES.md
- [X] Query runs without errors
- [X] Query output is correct
- [X] Query logic is clear and well documented
- [X] Query is readable and properly indented with spaces (not tabs)
- [X] Table and column names are in all-lowercase
- [X] Quotation marks are used only where necessary

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [X] File name is listed in `runlist.txt` after dependencies
- [X] All columns have indexes
- [X] Table is vacuumed and analyzed

Looks good! Please insert that one line again (see comment) and add the change to the CHANGE.md file on the root level.

2022-10-20 10:28 UTC, stdombek commented on sql_metadb/derived_tables/licenses_license_ext.sql
> --- Create a derived table that contains information about licenses from the app license
Please paste this line again.

2022-10-21 07:11 UTC, stdombek approved these changes

2022-10-27 21:37 UTC, amzoss approved these changes
Thanks, looks good!

All queries:
- [x] Release notes added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-11-06 13:32 UTC, nassibnassar commented on CHANGES.md
> +* Comment on Columns added to licenses_ext from API Documentation
This should be: `licenses_license_ext`

2022-11-06 13:33 UTC, merged