Update po_line_fund_distribution_transactions.sql
folio-org/folio-analytics pull request #681
Opened 2022-10-17 18:29 UTC by AlaoSUL

Comment on Columns with descriptions from API Documentation

Closes #626 

```
All queries:
- [ ] Release notes added or updated in CHANGES.md
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented with spaces (not tabs)
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed
```

2022-10-21 17:52 UTC, jenmawe approved these changes
I read through the comments and saw the note in the changes.md file. As this query already existed and comments are being added, I didn't go through the entire process with the checkboxes.

2022-10-27 21:54 UTC, amzoss requested changes
Several problems with the comments commands. Even if you're not changing the main query, it's always a good idea to run the query yourself and make sure it executes without error.

All queries:
- [x] Release notes added or updated in CHANGES.md
- [ ] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-10-27 21:54 UTC, amzoss commented on sql_metadb/derived_tables/po_line_fund_distribution_transactions.sql
> +COMMENT ON COLUMN po_line_fund_distribution_transactions.poline_listUnitPrice IS 'The per-item list price for physical or resources of \'Other\' order format';
`\'` causes an error

2022-10-27 21:54 UTC, amzoss commented on sql_metadb/derived_tables/po_line_fund_distribution_transactions.sql
> +COMMENT ON COLUMN po_line_fund_distribution_transactions.poline_quantityPhysical IS 'Quantity of physical items or resources of \'Other\' order format in this purchase order line';
`\'` causes an error

2022-10-27 21:54 UTC, amzoss commented on sql_metadb/derived_tables/po_line_fund_distribution_transactions.sql
> +COMMENT ON COLUMN po_line_fund_distribution_transactions.poline_id IS 'UUID identifying this purchase order line';
Typo in the name of the field. Should be `po_line_id`.

2022-10-27 21:54 UTC, amzoss commented on sql_metadb/derived_tables/po_line_fund_distribution_transactions.sql
> +COMMENT ON COLUMN po_line_fund_distribution_transactions.transaction_encumbrance_initial_amount IS 'The initial amount of this encumbrance. Shouldn\'t change once create';
`\'` causes an error

2022-10-27 21:55 UTC, amzoss commented
@jenmawe There can definitely be errors introduced, even if someone is just adding comments. I think reviewers should probably go ahead and execute the code anyway before approving.

2022-11-03 22:27 UTC, amzoss approved these changes
Thanks, works well now!

All queries:
- [x] Release notes added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-11-06 14:08 UTC, merged