changes to Metadb po_lines_locations.sql with comments added
folio-org/folio-analytics pull request #690
Opened 2022-10-25 19:08 UTC by natalyapik

```
All queries:
- [ ] Release notes added or updated in CHANGES.md
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented with spaces (not tabs)
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed
```

2022-10-27 14:48 UTC, adoerrer requested changes
There are some Typos in the field name which causes the query not to run. And there's is additional query which updates the comments which need to be mentioned in the Changes.md

All queries:
- [ ] Release notes added or updated in CHANGES.md
- [ ] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-10-27 14:48 UTC, adoerrer commented on CHANGES.md
>  * A new derived table for LDP 1.x, `instance_administrative_notes`,
If you want to leave  the  updated holdings_administrative_notes.sql on comments in this PR. We need to have it mentioned in the Changes.md as well.

2022-10-27 14:48 UTC, adoerrer commented on sql_metadb/derived_tables/po_lines_location.sql
> +    LEFT JOIN folio_inventory.holdings_record__t AS hr ON ploc.pol_hold_id::uuid= hr.id
Typo in `ploc.pol_hold_id` should be `ploc.pol_holding_id`

This prevents the query to run.

2022-10-27 14:48 UTC, adoerrer commented on sql_metadb/derived_tables/po_lines_location.sql
> +CASE WHEN ploc.pol_loc_id IS NOT NULL THEN ploc.pol_loc_id
Typo `ploc.pol_loc_id` should be  `ploc.pol_location_id`

2022-10-27 14:48 UTC, adoerrer commented on sql_metadb/derived_tables/po_lines_location.sql
> +    LEFT JOIN folio_inventory.location__t AS loc ON loc.id = ploc.pol_loc_id
Typo `ploc.pol_loc_id` should be `ploc.pol_location_id`

2022-11-03 22:32 UTC, amzoss commented
@natalyapik if you want to "remove" the holdings_administrative_notes.sql file from this PR, you could add a commit that edits that file back to the currently approved version of the query: https://github.com/folio-org/folio-analytics/blob/main/sql_metadb/derived_tables/holdings_administrative_notes.sql

2022-11-04 20:20 UTC, amzoss commented
And, in case it's not clear, I'm waiting to review this query until previously mentioned issues are addressed.

2022-11-07 15:27 UTC, closed without merging