Bugfix: Add missing encumbrance status to derived table `finance_trancaction_purchase_order`
folio-org/folio-analytics pull request #705
Opened 2022-11-28 14:31 UTC by adoerrer

This bugfix adds the missing encumbrance status to derived table `finance_trancaction_purchase_order` which is essential for particular reporting needs. 
Because LDP1 version is also needed to be fixed missing comments have been copied as well.

```
All queries:
- [ ] Release notes added or updated in CHANGES.md
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented with spaces (not tabs)
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed
```

2022-12-02 00:03 UTC, amzoss requested changes
This change also adds comments to LDP1 version, so that should be added to `CHANGES.md`. Otherwise looks good!

Checklist for LDP1 version:

All queries:
- [ ] Release notes added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

Checklist for Metadb version:

All queries:
- [ ] Release notes added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-12-05 15:16 UTC, adoerrer commented
Thank you @amzoss for making me aware of the missing Changes.md notes. 
This is now fixed.

2022-12-05 15:19 UTC, stdombek approved these changes
**LDP1 / Metadb version**
- [X] Release notes added or updated in CHANGES.md
- [X] Query runs without errors
- [X] Query output is correct
- [X] Query logic is clear and well documented
- [X] Query is readable and properly indented with spaces (not tabs)
- [X] Table and column names are in all-lowercase
- [X] Quotation marks are used only where necessary

Derived tables:
- [X] Query begins with user documentation in comment lines
- [X] File name is listed in `runlist.txt` after dependencies
- [X] All columns have indexes
- [X] Table is vacuumed and analyzed

The required tables can be deleted at the beginning in the comments. This is from an earlier time.

2022-12-05 15:35 UTC, adoerrer commented
Thanks @stdombek! I've removed the required tables from the documentation section now.

2022-12-05 15:36 UTC, stdombek approved these changes

2022-12-05 16:38 UTC, amzoss approved these changes
All looks great now, thanks!

All queries:
- [x] Release notes added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

2022-12-05 23:11 UTC, merged