Update LDP instance_publication derived table
folio-org/folio-analytics pull request #796
Opened 2023-09-19 18:31 UTC by natalyapik

add two new fields "ordinality" and "role", and comments as well

2023-10-31 10:46 UTC, LauSchl requested changes
The query has some minor issues including finding the columns (see comment on line 27).
Maybe the role could also be added to the documentation line at the beginning of the query. 

All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [ ] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

2023-10-31 10:46 UTC, LauSchl commented on sql/derived_tables/instance_publication.sql
> +    publication.ordinality AS publication_ordinality,
redundant comma

2023-10-31 10:46 UTC, LauSchl commented on sql/derived_tables/instance_publication.sql
> +COMMENT ON COLUMN instance_publication.ordinality IS 'Publication value ordinality';
the column names are currently publication_role and publication_ordinality (instead of role and ordinality)

2023-11-01 21:16 UTC, VandanaShah-Cornell requested changes
Need to remove the comma at the end of publication.ordinality AS publication_ordinality, else the query won't run.

2023-11-08 11:29 UTC, LauSchl approved these changes
runs great now :)
All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

2023-11-27 16:19 UTC, nassibnassar commented
@VandanaShah-Cornell Are you approving this PR?

2023-11-27 16:21 UTC, VandanaShah-Cornell commented
Sorry - will do it now

From: Nassib Nassar ***@***.***>
Sent: Monday, November 27, 2023 11:20 AM
To: folio-org/folio-analytics ***@***.***>
Cc: Vandana Suresh Shah ***@***.***>; Mention ***@***.***>
Subject: Re: [folio-org/folio-analytics] Update LDP instance_publication derived table (PR #796)


@VandanaShah-Cornell<https://github.com/VandanaShah-Cornell> Are you approving this PR?

-
Reply to this email directly, view it on GitHub<https://github.com/folio-org/folio-analytics/pull/796#issuecomment-1828163701>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMK23BTB6LI3G5IDVRJZ553YGS4S5AVCNFSM6AAAAAA46XKETOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRYGE3DGNZQGE>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2023-11-27 16:45 UTC, merged