ACQ - Updates to derived table "finance_transactions_purchase_orders.sql" for Metadb
folio-org/folio-analytics pull request #805
Opened 2023-10-26 19:40 UTC by sbeltaine

Closes #797
Added transaction_expense_class_code, transaction_expense_class_name, and external_account_number_ext. Please note that finance_transactions_purchase_orders.sql is already included in the runlist.txt file for Metadb.

Documented this update on the 1.7 (Poppy) release notes at https://github.com/folio-org/folio-analytics/wiki/Changes-by-Release

2023-10-30 12:46 UTC, stdombek requested changes
All queries:
- [X] PR Title and Description are accurate and thorough
- [X] PR is based on a new branch (not main)
- [X] PR scope is not overly broad
- [X] Query runs without errors
- [X] Query output is correct
- [X] Query logic is clear and well documented
- [X] Query is readable and properly indented
- [X] Table and column names are in all-lowercase
- [X] Quotation marks are used only where necessary
- [X] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [X] First line is "--metadb:table" directive, followed by blank line
- [X] User documentation in comment lines, followed by blank line
- [X] File name is listed in `runlist.txt` after dependencies

**Query is very good, only 2 empty lines can be deleted. **

2023-10-30 12:46 UTC, stdombek commented on sql_metadb/derived_tables/finance_transaction_purchase_order.sql
> +
Empty line can be deleted.

2023-10-30 12:46 UTC, stdombek commented on sql_metadb/derived_tables/finance_transaction_purchase_order.sql
> +
Empty line can be deleted.

2023-10-30 13:09 UTC, stdombek commented
I only see one problem if I'm not wrong. For the query to work there must always be a table for the expense class? Metadb creates the table only if expense classes there? This is the same issue as the finance_invoice_transactions derived table in PR https://github.com/folio-org/folio-analytics/pull/803 We should definitely check this. @nassibnassar ?

2023-10-30 13:35 UTC, nassibnassar commented
The `--metadb:require` directive can be used to ensure the required table and column(s) are present: https://metadb.dev/doc/#_metadbrequire

2023-10-31 16:43 UTC, sbeltaine commented on sql_metadb/derived_tables/finance_transaction_purchase_order.sql
> +
Done.

2023-10-31 16:43 UTC, sbeltaine commented on sql_metadb/derived_tables/finance_transaction_purchase_order.sql
> +
Done.

2023-11-01 04:07 UTC, trapido approved these changes
The require directive for the expense classes table has been added, so everything looks good!

All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [x] First line is "--metadb:table" directive, followed by blank line
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

2023-11-01 09:38 UTC, stdombek approved these changes

2023-11-10 02:52 UTC, merged