ACQ - Updates to derived table "finance_transactions_purchase_orders.sql" for LDP
folio-org/folio-analytics pull request #808
Opened 2023-10-28 00:06 UTC by sbeltaine

Closes #807

Added transaction_expense_class_code, transaction_expense_class_name, and external_account_number. Please note that finance_transactions_purchase_orders.sql is already included in the runlist.txt file for LDP.

Documented this update on the 1.7 (Poppy) release notes at https://github.com/folio-org/folio-analytics/wiki/Changes-by-Release

2023-10-31 11:16 UTC, LauSchl approved these changes
works great 👍 
All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

2023-11-03 18:27 UTC, trapido approved these changes
Looks great!

- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

2023-11-10 03:07 UTC, nassibnassar requested changes

2023-11-10 03:07 UTC, nassibnassar commented on sql/derived_tables/finance_transaction_purchase_order.sql
> +    ec.data #>> '{name}'AS transaction_expense_class_name,
Although not strictly necessary, it would be good I think to add a space before `AS`.

2023-11-10 03:07 UTC, nassibnassar commented on sql/derived_tables/finance_transaction_purchase_order.sql
> +
I suggest not using blank lines in a query.

2023-11-10 03:07 UTC, nassibnassar commented on sql/derived_tables/finance_transaction_purchase_order.sql
> +
Again I would remove the blank line.

2023-11-10 23:21 UTC, merged